[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

[".config/tmux/plugins/catppuccin"]
type = "archive"
url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.2.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

["karabiner"]
type = "git-repo"
url = "https://github.com/mehrad-meraji/karabiner"
refreshPeriod = "168h"

["nvim"]
type = "git-repo"
url = "https://github.com/mehrad-meraji/nvim"
refreshPeriod = "168h"

