[homebrew]
taps = []
brews = [
  "age",
  "ansible",
  "direnv",
  "bat",
  "bat-extras",
  "bitwarden-cli",
  "chezmoi",
  "composer",
  "eza",
  "ffmpeg",
  "fish",
  "fd",
  "fzf",
  "gh",
  "git",
  "gnupg",
  "htop",
  "lazygit",
  "jq",
  "libpq",
  "mise",
  "neovim",
  "nx",
  "opencode",
  "opentofu",
  "pnpm",
  "postgresql@14",
  "rbw",
  "ripgrep",
  "rustup",
  "tmux",
  "starship",
  "zellij",
  "zoxide",
  "zsh",
]
casks = [
  "alacritty",
  "appcleaner",
  "bitwarden",
  "dbngin",
  "figma",
  "font-jetbrains-mono-nerd-font",
  "git-credential-manager",
  "google-chrome",
  "karabiner-elements",
  "logi-options+",
  "obsidian",
  "ollama-app",
  "raycast",
  "sf-symbols",
  "signal",
  "sketch",
  "slack",
  "stats",
  "tailscale-app",
  "vlc",
  "webpquicklook",
  "zed",
]
