set -g default-terminal "alacritty"
set-option -sa terminal-features ',xterm*:RGB'
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-shell "/opt/homebrew/bin/fish"

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g @t-fzf-prompt '  '
set -g @p `pwd`

set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g status-position top

# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session

# Set new panes to open in current directory
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Run plugin
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

# Make the status line more pleasant.
set -g window-status-separator ""
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold]TMUX (#S) "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# init tmp - keep at end of file
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"

run '$HOME/.tmux/plugins/tpm/tpm'
